version: '3'

services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    ports:
      - "6596:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    build:
      context: ./
      # dockerfile: Dockerfile
    image: wordpress:latest
    depends_on:
      - db
    volumes:
      - wp_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_PREFIX: wp_
      WORDPRESS_DEBUG: "true"
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME',  "http://{$$_SERVER['HTTP_HOST']}");
        define('WP_SITEURL', "http://{$$_SERVER['HTTP_HOST']}");
        ob_start( 'ob_replace_home_url' );
        function ob_replace_home_url( $$content ) {
        $$home_urls = array(
        'http://asteriski.fi',
        'http://www.asteriski.fi',
        'http://asteriski.utu.fi',
        'https://asteriski.fi',
        'https://www.asteriski.fi',
        'https://asteriski.utu.fi',
        );
        $$content = str_replace( $$home_urls, WP_HOME, $$content );
        return $$content;
        }

  cli:
    image: wordpress:cli
    user: xfs
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
      - db

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress


volumes:
  db_data:
  wp_data:
